import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import localFont from 'next/font/local'
import type { Metadata } from "next";
import QueryProvider from "@/providers/QueryProvider";


const iransans = localFont({
  src:'../../public/fonts/iransans.ttf' ,
  variable: '--font-iransans'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" >
      <body
        className={`${iransans.variable} antialiased`}
      >
        <QueryProvider>
           <Theme>
            <main>
            {children}
           </main>
          </Theme>
        </QueryProvider>
      </body>
    </html>
  );
}
